import type { Template } from "./types";

// Four starter templates the user can use as a reference (and, later, fork in
// the visual editor). Two kinds × two depths:
//   simple-memo / full-memo  — the Quick Memo flow
//   simple-ic   / full-ic    — the Full IC Report flow
//
// Each generated block carries the prompt that will fill it; `sample` holds
// representative copy used only for the read-only gallery preview. Samples are
// fictional — no real deal data.

export const STARTER_TEMPLATES: Template[] = [
  {
    id: "simple-memo",
    name: "Simple memo",
    nameKey: "starter.simpleMemoName",
    kind: "memo",
    variant: "simple",
    description: "A one-pager: company, thesis, risks, and the call. ~5 minutes.",
    descriptionKey: "starter.simpleMemoDesc",
    page: { font: "editorial", accent: "gold", showLogo: false },
    blocks: [
      {
        id: "sm-head",
        type: "heading",
        label: "Company",
        labelKey: "starter.blockCompany",
        width: "full",
        style: { font: "editorial", size: "xl", weight: "medium" },
        content: { mode: "generated", prompt: "State the company name and a one-line description of what it does." },
        sample: { text: "Acme Robotics — autonomous warehouse pickers for mid-market 3PLs." },
      },
      {
        id: "sm-snap",
        type: "metrics",
        label: "Snapshot",
        labelKey: "starter.blockSnapshot",
        width: "full",
        content: { mode: "generated", prompt: "Pull stage, the round size being raised, and sector into three short metrics." },
        sample: { metrics: [{ label: "Stage", value: "Seed" }, { label: "Raising", value: "$3M" }, { label: "Sector", value: "Robotics" }] },
      },
      {
        id: "sm-thesis",
        type: "bullets",
        label: "Thesis",
        labelKey: "starter.blockThesis",
        width: "full",
        content: { mode: "generated", prompt: "3–4 bullets on why this could win: the wedge, the unfair advantage, why now." },
        sample: { bullets: ["Labor shortage is forcing mid-market 3PLs to automate now", "Founders shipped the same arm at a tier-1 logistics company", "~30% cheaper per pick than the incumbent arms"] },
      },
      {
        id: "sm-risks",
        type: "bullets",
        label: "Risks",
        labelKey: "starter.blockRisks",
        width: "full",
        style: { accent: "crimson" },
        content: { mode: "generated", prompt: "2–3 real deal-breakers — the things that would actually kill this, not generic risk." },
        sample: { bullets: ["Hardware gross margin unproven at volume", "One paying pilot = heavy customer concentration"] },
      },
      {
        id: "sm-call",
        type: "paragraph",
        label: "Recommendation",
        labelKey: "starter.blockRecommendation",
        width: "full",
        style: { accent: "teal" },
        content: { mode: "generated", prompt: "Two sentences: take a first meeting or pass, and the single condition that would change your mind." },
        sample: { text: "Worth a first meeting — the team is credible and the wedge is real. Pass if the second pilot doesn't convert to paid within the quarter." },
      },
    ],
  },

  {
    id: "full-memo",
    name: "Full memo",
    nameKey: "starter.fullMemoName",
    kind: "memo",
    variant: "full",
    description: "A two-page structured memo with metrics, market, risks, and a score.",
    descriptionKey: "starter.fullMemoDesc",
    page: { font: "editorial", accent: "gold", showLogo: true },
    blocks: [
      {
        id: "fm-logo",
        type: "logo",
        label: "Logo",
        labelKey: "starter.blockLogo",
        width: "full",
        content: { mode: "static", text: "Firm logo", textKey: "starter.staticFirmLogo" },
      },
      {
        id: "fm-head",
        type: "heading",
        label: "Company",
        labelKey: "starter.blockCompany",
        width: "full",
        style: { font: "editorial", size: "xl", weight: "medium" },
        content: { mode: "generated", prompt: "Company name and a one-line description." },
        sample: { text: "Acme Robotics — autonomous warehouse pickers for mid-market 3PLs." },
      },
      {
        id: "fm-metrics",
        type: "metrics",
        label: "At a glance",
        labelKey: "starter.blockAtAGlance",
        width: "full",
        content: { mode: "generated", prompt: "Four metrics: ARR, monthly burn, runway, and the round being raised." },
        sample: { metrics: [{ label: "ARR", value: "$1.4M" }, { label: "Burn", value: "$180k/mo" }, { label: "Runway", value: "14 mo" }, { label: "Raising", value: "$3M" }] },
      },
      {
        id: "fm-what",
        type: "paragraph",
        label: "What they do",
        labelKey: "starter.blockWhatTheyDo",
        width: "full",
        content: { mode: "generated", prompt: "One paragraph on the product and who buys it. Plain, concrete, no hype." },
        sample: { text: "Acme builds a vision-guided picking arm and the software that runs it, sold to third-party logistics operators who can't hire enough seasonal labor. It drops into existing shelving without a warehouse rebuild." },
      },
      {
        id: "fm-market",
        type: "paragraph",
        label: "Market",
        labelKey: "starter.blockMarket",
        width: "full",
        content: { mode: "generated", prompt: "One paragraph on market size, growth, and the incumbents being displaced." },
        sample: { text: "Mid-market 3PL automation is a ~$12B segment growing low-double-digits as labor costs rise. Incumbent arms target enterprise DCs and are too expensive and too slow to deploy for this tier." },
      },
      {
        id: "fm-why",
        type: "bullets",
        label: "Why now",
        labelKey: "starter.blockWhyNow",
        width: "full",
        content: { mode: "generated", prompt: "3–4 bullets on timing and the unfair advantage." },
        sample: { bullets: ["Vision models finally good enough for mixed-SKU bins", "Labor cost per pick up 40% in three years", "Founding team's incumbent relationships open the first ten logos"] },
      },
      {
        id: "fm-risks",
        type: "bullets",
        label: "Risks",
        labelKey: "starter.blockRisks",
        width: "full",
        style: { accent: "crimson" },
        content: { mode: "generated", prompt: "3 real deal-breakers, ranked by how much they'd move the decision." },
        sample: { bullets: ["Hardware margin unproven at volume", "Long sales cycles vs short runway", "Incumbents could cut price into this tier"] },
      },
      {
        id: "fm-rec",
        type: "paragraph",
        label: "Recommendation",
        labelKey: "starter.blockRecommendation",
        width: "full",
        style: { accent: "teal" },
        content: { mode: "generated", prompt: "Take or pass, the check size, and the one diligence item that gates it." },
        sample: { text: "Lean in for a $500k check, gated on a reference call with the paying pilot. The team and timing carry it; the open question is unit economics at the second site." },
      },
      {
        id: "fm-score",
        type: "scoreBox",
        label: "Score",
        labelKey: "starter.blockScore",
        width: "full",
        content: { mode: "generated", prompt: "A single overall score out of 10 with a one-line justification." },
        sample: { score: { label: "Overall", value: "7.5 / 10" }, caption: "Strong team and timing; hardware margin is the swing factor." },
      },
    ],
  },

  {
    id: "simple-ic",
    name: "Simple IC",
    nameKey: "starter.simpleIcName",
    kind: "ic",
    variant: "simple",
    description: "Three passes — founder, market, recommendation — plus a score. ~10 minutes.",
    descriptionKey: "starter.simpleIcDesc",
    page: { font: "editorial", accent: "teal", showLogo: false },
    blocks: [
      {
        id: "si-head",
        type: "heading",
        label: "Company",
        labelKey: "starter.blockCompany",
        width: "full",
        style: { font: "editorial", size: "xl", weight: "medium" },
        content: { mode: "generated", prompt: "Company name and a one-line description." },
        sample: { text: "Acme Robotics — autonomous warehouse pickers for mid-market 3PLs." },
      },
      {
        id: "si-founder",
        type: "paragraph",
        label: "Founder & team",
        labelKey: "starter.blockFounderTeam",
        width: "full",
        content: { mode: "generated", prompt: "Summarize the founding team. Lead with prior exits and technical depth. 3–4 sentences, no hype." },
        sample: { text: "Two-time founder; prior picking-arm company acquired by a tier-1 logistics player. CTO led the perception stack there. Small but unusually senior team for the stage." },
      },
      {
        id: "si-market",
        type: "paragraph",
        label: "Market",
        labelKey: "starter.blockMarket",
        width: "full",
        content: { mode: "generated", prompt: "Market size, growth, and who they displace. Name the incumbents." },
        sample: { text: "~$12B mid-market 3PL automation, growing low-double-digits. Incumbents (Berkshire Grey, Dexterity) aim upmarket and deploy too slowly for this tier." },
      },
      {
        id: "si-rec",
        type: "paragraph",
        label: "Recommendation",
        labelKey: "starter.blockRecommendation",
        width: "full",
        style: { accent: "teal" },
        content: { mode: "generated", prompt: "The call and the one condition that gates it. Two sentences." },
        sample: { text: "Recommend a first meeting and a reference call. The wedge is real; the gate is whether the pilot renews at full price." },
      },
      {
        id: "si-score",
        type: "scoreBox",
        label: "Score",
        labelKey: "starter.blockScore",
        width: "full",
        content: { mode: "generated", prompt: "Overall score out of 10 with a one-line reason." },
        sample: { score: { label: "Overall", value: "7 / 10" }, caption: "Credible team, real wedge, unproven margin." },
      },
    ],
  },

  {
    id: "full-ic",
    name: "Full IC",
    nameKey: "starter.fullIcName",
    kind: "ic",
    variant: "full",
    description: "Five sections with sub-blocks — founder, market, traction, terms, recommendation — plus charts and a score. ~30 minutes.",
    descriptionKey: "starter.fullIcDesc",
    page: { font: "editorial", accent: "teal", showLogo: true },
    blocks: [
      {
        id: "fi-cover",
        type: "cover",
        label: "Cover",
        labelKey: "starter.blockCover",
        width: "full",
        style: { align: "center" },
        content: { mode: "generated", prompt: "Company name as the title, with 'Investment Committee Memo' and the date as the subtitle." },
        sample: { text: "Acme Robotics", caption: "Investment Committee Memo · Confidential" },
      },
      {
        id: "fi-terms-metrics",
        type: "metrics",
        label: "Deal snapshot",
        labelKey: "starter.blockDealSnapshot",
        width: "full",
        content: { mode: "generated", prompt: "Four metrics: stage, round size, pre-money valuation, and proposed check." },
        sample: { metrics: [{ label: "Stage", value: "Seed" }, { label: "Round", value: "$3M" }, { label: "Pre-money", value: "$12M" }, { label: "Our check", value: "$500k" }] },
      },
      {
        id: "fi-founder",
        type: "paragraph",
        label: "Founder & team",
        labelKey: "starter.blockFounderTeam",
        width: "full",
        content: { mode: "generated", prompt: "Founding team: prior exits, technical depth, gaps. Be specific and even-handed." },
        sample: { text: "CEO is a two-time founder whose last picking-arm company was acquired by a tier-1 logistics player; CTO led perception there. The team is senior for the stage but thin on go-to-market hires, which the round is meant to fix." },
      },
      {
        id: "fi-market",
        type: "paragraph",
        label: "Market",
        labelKey: "starter.blockMarket",
        width: "full",
        content: { mode: "generated", prompt: "Market size, growth drivers, segmentation, and the incumbents being displaced." },
        sample: { text: "Mid-market 3PL automation is ~$12B and growing low-double-digits as labor costs climb. The segment is underserved: enterprise-grade arms are too costly and slow to deploy here." },
      },
      {
        id: "fi-market-chart",
        type: "chart",
        label: "Market size (TAM / SAM / SOM)",
        labelKey: "starter.blockMarketSize",
        width: "full",
        content: { mode: "generated", prompt: "A bar chart of TAM, SAM, and reachable SOM in USD billions." },
        sample: { chart: [{ label: "TAM", value: 12 }, { label: "SAM", value: 4.5 }, { label: "SOM", value: 0.9 }], caption: "USD billions" },
      },
      {
        id: "fi-traction",
        type: "paragraph",
        label: "Product & traction",
        labelKey: "starter.blockProductTraction",
        width: "full",
        content: { mode: "generated", prompt: "Product maturity and traction: deployments, revenue, retention, pipeline." },
        sample: { text: "One paid deployment live nine months, a second in pilot. Picks-per-hour beats the customer's manual baseline by 35%. Pipeline is early but warm via founder relationships." },
      },
      {
        id: "fi-traction-metrics",
        type: "metrics",
        label: "Traction",
        labelKey: "starter.blockTraction",
        width: "full",
        content: { mode: "generated", prompt: "Four metrics: ARR, year-over-year growth, net revenue retention, and number of paying logos." },
        sample: { metrics: [{ label: "ARR", value: "$1.4M" }, { label: "YoY", value: "+180%" }, { label: "NRR", value: "115%" }, { label: "Logos", value: "1 paid" }] },
      },
      {
        id: "fi-terms",
        type: "paragraph",
        label: "Round & terms",
        labelKey: "starter.blockRoundTerms",
        width: "full",
        content: { mode: "generated", prompt: "Round structure, instrument, valuation, key terms, and who else is in." },
        sample: { text: "$3M priced seed at $12M pre, standard terms, one board seat to the lead. A strategic logistics angel is committed for $250k. Pro-rata rights included." },
      },
      {
        id: "fi-cap",
        type: "table",
        label: "Cap table & terms",
        labelKey: "starter.blockCapTable",
        width: "full",
        content: { mode: "generated", prompt: "A small table of the post-round cap table: holder, instrument, and ownership %." },
        sample: { rows: [["Holder", "Instrument", "Ownership"], ["Founders", "Common", "62%"], ["Seed lead", "Preferred", "18%"], ["Option pool", "—", "12%"], ["Angels", "SAFE", "8%"]] },
      },
      {
        id: "fi-rec",
        type: "paragraph",
        label: "Recommendation",
        labelKey: "starter.blockRecommendation",
        width: "full",
        style: { accent: "teal" },
        content: { mode: "generated", prompt: "The decision, the check, the conditions, and what would make us pass. Be decisive." },
        sample: { text: "Recommend a $500k check, conditional on a reference call with the paying pilot and a teardown of second-site unit economics. Pass if margin at the second site is below 25%." },
      },
      {
        id: "fi-score",
        type: "scoreBox",
        label: "Score",
        labelKey: "starter.blockScore",
        width: "full",
        content: { mode: "generated", prompt: "Overall score out of 10 plus sub-scores for team, market, and traction." },
        sample: { score: { label: "Overall", value: "7.5 / 10" }, caption: "Team 8 · Market 7 · Traction 6 — margin is the swing factor." },
      },
    ],
  },
];
